### ISSUE TITLE
Yii2 

### ISSUE THREAD

**Issue by isaygo** [Bogdaan/viber-bot-php#1]
How can i integrate viber-bot-php into yii2 action. Many ways, many errors

500
400
i tried _csrf off
now i hav ActiveControoler and with message 'Response content must not be an array.' 

In standalone php app the work is OK.

**Comment by Bogdaan** [comment]
First - you dont need put bot code inside controller. 

a) You can put yii-related initialization inside bot hook **web/bot.php**:
```
defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

// <--- init yii if you need
// $config = require(__DIR__ . '/../config/web.php');
// $app = (new yii\web\Application($config));

// <--- init bot
```

b) disable csrf inside beforeAction and disable debug mode:
```
public function beforeAction($action) {
    // esure YII_DEBUG OFF
    $this->enableCsrfValidation = false;
    return parent::beforeAction($action);
}
```

**Comment by isaygo** [comment]
Sorry for stoling your time, i'm new in yii2
`<?php
namespace frontend\controllers;
use Yii;

use common\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
//use common\extensions\viber\Viberbot;
use Viber\Bot;
use Viber\Api\Sender;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use yii\rest\ActiveController;
//ADDED FOR AUTHENTIFICATION WITH BEHAVIORS
use yii\filters\AccessControl;
use yii\helpers\Json;
/**
 * UsersController implements the CRUD actions for Users model.
 */
class ViberController extends ActiveController
{
	public $modelClass = 'common\models\Users';

     public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
				//'only' => ['index', 'signup'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
						'roles' => ['?'],
                    ],
                    [
                        
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],		
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['GET','POST','HEAD'],
                ],
            ],
        ];
    } 
public function actionIndex()
{
			Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			$apiKey = '45942c46e2349e6b-d87008735d9b7257-af19e13d2236196b';
            $botSender = new Sender([
    //'name' => 'Whois bot',
    //'avatar' => 'https://developers.viber.com/img/favicon.ico',
     ]);
try {
    $bot = new Bot(['token' => $apiKey]);
    $bot
    ->onConversation(function ($event) use ($bot, $botSender) {
        // это событие будет вызвано, как только пользователь перейдет в чат
        // вы можете отправить "привествие", но не можете посылать более сообщений
        return (new \Viber\Api\Message\Text())
            ->setSender($botSender)
            ->setText("Can i help you?");
    })
    ->onText('|\d{1}|is', function ($event) use ($bot, $botSender) {
        // это событие будет вызвано если пользователь пошлет сообщение 
        // которое совпадет с регулярным выражением
        $bot->getClient()->sendMessage(
            (new \Viber\Api\Message\Text())
            ->setSender($botSender)
            ->setReceiver($event->getSender()->getId())
            ->setText("I do not know YO!)")
        );
    })
    ->run();
} catch (Exception $e) {
    // todo - log exceptions
}		
    }	
      public function beforeAction($action) {
        if($action->id === 'index'){
			Yii::$app->controller->enableCsrfValidation = false;
		} 
        return parent::beforeAction($action);
    }  	  
}
`

and i have the error:

> exception 'yii\base\InvalidParamException' with message 'Response content must not be an array.' in /home/saygo/i-link.net.ua/billing/vendor/yiisoft/yii2/web/Response.php:1020

Seems that bot is working, but cant fly right response

**Comment by Bogdaan** [comment]
Sory, but i unable to read this spaghetti code. Please use pastebin or gist.
PHP functions return value from last op. Therefore you need ```return``` or ```exit``` op at the end of action function (better ***app()->end()**).

```
<?php
,,,,
public function actionIndex()
{
  // -- bot ops
  return '';
}
```

Note you must specify `Content-type: application/json` header (as I explained above)
