### ISSUE TITLE
Uncaught RuntimeException: HTTP_X_VIBER_CONTENT_SIGNATURE header not found

### ISSUE THREAD

**Issue by 24tech** [Bogdaan/viber-bot-php#14]
После установки Webhook выдает такую ошибку.
`Fatal error: Uncaught RuntimeException: HTTP_X_VIBER_CONTENT_SIGNATURE header not found in /storage/ssd1/364/3374364/public_html/src/Bot.php:136 Stack trace: #0 /storage/ssd1/364/3374364/public_html/examples/bot-plus.php(207): Viber\Bot->getSignHeaderValue() #1 {main} thrown in /storage/ssd1/364/3374364/public_html/src/Bot.php on line 136`
Веб сервер работает по https с корректным SSL сертификатом.
![2017-10-24_173238](https://user-images.githubusercontent.com/16729976/31943218-7d6ab85e-b8e1-11e7-9f13-124031c6db68.png)
Что делать?

**Comment by Bogdaan** [comment]
Так и задумано.
Нет смысла посещать скрипт бота из браузера

**Comment by 24tech** [comment]
решил проблему с помощью thedebuggers.com
[](http://thedebuggers.com/build-viber-chat-bot-6-simple-steps/)

**Comment by Bogdaan** [comment]
https://github.com/Bogdaan/viber-bot-php/blob/master/docs/first-steps.md
