### ISSUE TITLE
Не могу установить веб хук

### ISSUE THREAD

**Issue by verdysh** [Bogdaan/viber-bot-php#25]
Привет!

Скачал архив с Гитхаба. Пробую выполнить examples/setup.php, но получаю ошибку об отсутствии файла ../vendor/autoload.php.

Warning: require_once(../vendor/autoload.php): failed to open stream: No such file or directory in ...\examples\setup.php on line 10

Его действительно нету, как и папки vendor. Я так понимаю, они появятся если загрузить проект через Композер. Но мои попытки сделать это, успехом не увенчались.

Вы бы не могли выложить архив, который получается в результате скачивания проекта Композером? Ну или что-нибудь, чтобы оно заработало :)

**Comment by Bogdaan** [comment]
see https://getcomposer.org/doc/00-intro.md
