### ISSUE TITLE
HTTP_X_VIBER_CONTENT_SIGNATURE header not found

### ISSUE THREAD

**Issue by Alimgulov** [Bogdaan/viber-bot-php#3]
При установки webhook выдает 500 ошибку (HTTP_X_VIBER_CONTENT_SIGNATURE header not found).
Как с этим бороться?

**Comment by Bogdaan** [comment]
"При установки"
как это понимать?

В коде установке хука этого нет. Проверка заголовка есть в вызове - https://github.com/Bogdaan/viber-bot-php/blob/41f809e560c139344b865f78d804b7a34e83e88c/src/Bot.php#L133

**Comment by Bogdaan** [comment]
Просмотрите этот раздел:
https://github.com/Bogdaan/viber-bot-php/blob/master/docs/first-steps.md#setup-webhook

Этот код можно запустить как через cli так и cgi

**Comment by Alimgulov** [comment]
`$viberBot = new Client([
            'token' => $this->viber_token,
        ]);

        $viberBot->setWebhook($url);`
вот тут срабатывает эта ошибка. 
Как я понял, viber сам отправляет запрос на вх, когда его устанавливаешь. 
И вот при этом запросе, вылетает ошибка. 
Но, если установить этот вх, то бот работает нормально. (но что бы установить этот вх, сама страница вх должна отдавать 200 код)

**Comment by Bogdaan** [comment]
Похоже вы неправильно понимаете схему взаимодействия.

1. вы устанавливаете webhook (вызов api) с адресом ***http://x.xx/x***
2. viber запоминает этот адрес
3. в дальнейшем viber будет присылать уведомление на адрес ***http://x.xx/x*** (на этом адресе НЕ нужно вызывать api которое снова устанавливает webhook - это бессмыслица)

**Comment by Alimgulov** [comment]
Once a set_webhook request is sent Viber will send a callback to the webhook to check its availability and return a response to the user.

Сам viber тоже отправляет запрос при установке webhook.

**Comment by Alimgulov** [comment]
и в вебхуке я не устанавливаю его опять )

**Comment by Bogdaan** [comment]
Тогда я не понимаю в чем именно у вас возникли сложности.
Если при вызове set_webhook - то какие?
Если при использовании кода бота - то вероятно вы некорректно установили url

**Comment by Alimgulov** [comment]
У меня есть 2 экшена.
1ый - установка вебкух
2ой - сам вебхук
Код 1ого:
`$viberBot = new Client([`
`    'token' => $this->viber_token,`
`]);`
``
`$viberBot->setWebhook($url);`

экшн вебхука:
`$bot = new Bot(['token' => $apiKey]);`
`$bot`
`->onConversation(function ($event) use ($bot, $botSender, $log) {`
`    $log->info('onConversation '. var_export($event, true));`
`    // this event fires if user open chat, you can return "welcome message"`
`    // to user, but you can't send more messages!`
`    return (new \Viber\Api\Message\Text())`
`        ->setSender($botSender)`
`        ->setText("Can i help you?");`
`})`
`->onText('|.*|s', function ($event) use ($bot, $botSender, $log) {`
`    $log->info('onText '. var_export($event, true));`
`    // .* - match any symbols`
`    $bot->getClient()->sendMessage(`
`        (new \Viber\Api\Message\Text())`
`        ->setSender($botSender)`
`        ->setReceiver($event->getSender()->getId())`
`        ->setText("HI!")`
`    );`
`})`
`->on(function ($event) {`
`    return true; // match all`
`}, function ($event) use ($log) {`
`    $log->info('Other event: '. var_export($event, true));`
`})`
`->run();`


Вот при вызове 1ого экшена, выдает ошибку

**Comment by beneyraheem** [comment]
I also have the same issue, or I dont know how to set this up.

I am using a domain, can you please explain easy way to run this script on a domain. (Web server)

**Comment by beneyraheem** [comment]
if ($bot) {
        $log->warning('Actual sign: '. $bot->getSignHeaderValue());
        $log->warning('Actual body: '. $bot->getInputBody());
    }

This lines of code gives me this error, but when I remover this line it works, also PHP version 7 need this script to work..
I dont know I did it correctly or not.

**Comment by Telegramsrv** [comment]
Извиняюсь что врываюсь, 
таким способом вебхук не снимается 
`$result = $client->setWebhook('');`
https://github.com/Bogdaan/viber-bot-php/issues/10
Invalid webhook url:

**Comment by Alimgulov** [comment]
`  if (!empty($_GET['sig']) && empty($_SERVER['HTTP_X_VIBER_CONTENT_SIGNATURE'])) {
            $_SERVER['HTTP_X_VIBER_CONTENT_SIGNATURE'] = $_GET['sig'];
        }`
в вебхук

**Comment by Bogdaan** [comment]
@Alimgulov thanks, fixed in https://github.com/Bogdaan/viber-bot-php/tree/0.0.5

**Comment by Niloofaar** [comment]
Добрый день Богдан! Когда пытаюсь запустить ваш bot-plus.php то тоже получаю следующую ошибку 
[2018-11-23 09:24:43] bot.WARNING: Exception: Signature header not found [] [] 
Который ссылается в файл Bot.php где есть : 
 public function getSignHeaderValue()
    {
        $signature = '';
        if (isset($_SERVER['HTTP_X_VIBER_CONTENT_SIGNATURE'])) {
            $signature = $_SERVER['HTTP_X_VIBER_CONTENT_SIGNATURE'];
        } elseif (isset($_GET['sig'])) {
            $signature = $_GET['sig'];
        }
        if (empty($signature)) {
            throw new \RuntimeException('Signature header not found', 1);
        }
        return $_SERVER[$headerName];
    }
Как быть в данной ситуации ? Помогите пожалуйста.
