### ISSUE TITLE
Не приходит message от пользователя

### ISSUE THREAD

**Issue by dabeedj** [Bogdaan/viber-bot-php#30]
Добрый день
Большое спасибо за SDK!
У меня file_get_contents("php://input") всегда пустой, когда пользователь отправляет боту сообщение.
При чем и HTTP заголовки и query string приходят как положено
В php.ini allow_url_fopen разрешен
Не подскажите, в чем может быть загвоздка?
Спасибо!

**Comment by dabeedj** [comment]
Спасибо за быстрый ответ!
Забыл упомянуть, $HTTP_RAW_POST_DATA и $_POST - тоже пустые. По $_GET приходит только сигнатура, в $_SERVER указано, что запрос от Viber - GET методом, что, как по мне, странно, я так понимаю, метод дожен был быть указан, как POST?
Натолкнуло меня на идею, что это может быть связано с SSL, я впервые работаю с ним, у меня установлен Let's encrypt.
Может быть попробую какой-то платный... Натолкнуло на мысль потому, что паралельно пытаюсь подключить Telegram, так тот вообще даже не стучится на WebHook...
Буду очень благодарен, если возникнут какие-либо мысли по поводу, так как мозг уже сломан:)

**Comment by Bogdaan** [comment]
В таком случае, есть вероятность того, что у вас некорректно настроен сервер.
Возможно вам стоит разобраться как работает tls / ssl. Ну а в качестве решения "прямо сейчас" предлагаю вам использовать https://www.ssllabs.com/ssltest/ для оценки качества настройки вашего сервера.

**Comment by dabeedj** [comment]
Вот такой результат
[https://www.ssllabs.com/ssltest/analyze.html?d=aptest.tugeza.pro&s=185.104.45.34](https://www.ssllabs.com/ssltest/analyze.html?d=aptest.tugeza.pro&s=185.104.45.34)
Если будет возможность глянуть - буду благодарен. 
Может быть связано с тем, что второй сертификат (как я понимаю, сертификат моего хостера) expired?

**Comment by dabeedj** [comment]
В общем у хостера была включена переадресация https -> http (lame me)
Telegram заработал... осталось найти причину с Viber, думаю, что справлюсь
В любом случае огромное спасибо за помощь! И еще раз за SDK

**Comment by dabeedj** [comment]
Viber тоже заработал:) Оказывается, надо было просто выспаться:) Спасибо еще раз!
