### ISSUE TITLE
Получение изображения и других типов сообщений ботом от пользователей

### ISSUE THREAD

**Issue by dabeedj** [Bogdaan/viber-bot-php#32]
Доброго времени суток.
Исходя из REST API существует возможность передачи боту таких типов сообщений
> text, picture, video, contact, URL and location

В SDK есть методы бота
> on, onText, onSubscribe, onConversation

Каким образом можно словить, например, изображение?
Спасибо!

**Comment by Bogdaan** [comment]
Довольно просто
```
// ... init $bot

$bot->on(function (Event $event)  {
            return (
                $event instanceof \Viber\Api\Event\Message
                && $event->getMessage() instanceof \Viber\Api\Message\Picture
            );
        }, function() {
           // <-- YOU HANDLER HERE
        });
```

https://github.com/Bogdaan/viber-bot-php/blob/master/src/Bot.php#L73

**Comment by dabeedj** [comment]
Спасибо огромное!
