### ISSUE TITLE
Media content in forwarded message

### ISSUE THREAD

**Issue by Smip** [Bogdaan/viber-bot-php#33]
Bot not receive links to media if user forwarded message to bot. 
For example, user sending forwarded message and bot receive next array:
```
[message:protected] => Viber\Api\Message\Picture Object
        (
            [text:protected] => 
            [media:protected] => 
            [thumbnail:protected] => 
            [receiver:protected] => 
            [type:protected] => picture
            [sender:protected] => 
            [tracking_data:protected] => 
            [min_api_version:protected] => 1
            [keyboard:protected] => 
            [propertiesMap:protected] => Array
                (
                )

        )
```
How to figure out what was sent and how to work with it I don't know. Have an idea?
Maybe problem not in your library but I'm confused.

====
Если пользователь пересылает сообщение с каким-то контентом (например изображение) то бот получает пустой объект с которым не понятно что делать и как его можно обрабатывать. Скорее всего это проблема не в библиотеке, а в апи вайбера, но может всё таки есть какие-то идеи как с этим бороться?

**Comment by Bogdaan** [comment]
Не встречал такого.
По плану приходит вот такое сообщение - https://developers.viber.com/docs/api/rest-bot-api/#picture-message

**Comment by Bogdaan** [comment]
Поле "text:protected" обязательное и всегда указывается со стороны VIber.

**Comment by Smip** [comment]
Да, такое сообщение приходит только если пользователь напрямую загрузил контент боту, и тут проблем нет. А вот если сообщение переслали то приходит пустота.

**Comment by Bogdaan** [comment]
А можете сделать копию запроса, который приходит на ваш сервер?
```
# in bot.php, $log - monolog instance
$log->addWarning('Foo: ' . var_export($_REQUEST, true));
```

**Comment by Smip** [comment]
$_REQUEST:
```
array (
  'sig' => '451b74243aca565db196fc3dd2e102337ac12718a3d146797da5894732555396',
)
```
file_get_contents('php://input'):
```
{
  "event":"message",
  "timestamp":1520171606164,
  "message_token":5151082750806091018,
  "sender":{
    "id":"<SENDER ID>",
    "name":"<SENDER NAME>",
    "avatar":"<LINK TO AVATAR>",
    "language":"en",
    "country":"UA",
    "api_version":2
  },
  "message":{
    "type":"picture"
  },
  "silent":false
}
```

**Comment by Bogdaan** [comment]
Не встречал подобного, но в любом случае, спасибо за информацию - пригодиться (в случае если у кого-нибудь данная ситуация проявиться).
