### ISSUE TITLE
А послать с php сайта сообщение на чей то viber можно?

### ISSUE THREAD

**Issue by anonym24** [Bogdaan/viber-bot-php#47]
А послать с php сайта сообщение на чей то viber можно?

типо как с функцией php mail

**Comment by aiera1993** [comment]
Конечно. Я записываю в базу все сообщения, которые пишут боту

**Comment by miyalisya** [comment]
Можно пример?

**Comment by Bogdaan** [comment]
послать можно только тем, кто подписался на ваш канал
