### ISSUE TITLE
Call Name

### ISSUE THREAD

**Issue by beneyraheem** [Bogdaan/viber-bot-php#5]
onConversation how to greet with the name. 

eg: Hi, (sender_name)

**Comment by Bogdaan** [comment]
Use getSender method:

```$event->getSender()```

See at https://github.com/Bogdaan/viber-bot-php/blob/master/examples/bot-plus.php#L70

Docs https://developers.viber.com/docs/api/rest-bot-api/#conversation-started

**Comment by beneyraheem** [comment]
I am sorry, 

But I can not get it work on, onConversation. (Welcome Message)

Can you please help
here is my code.


`    ->onConversation(function ($event) use ($bot, $botSender, $log) {
        $log->info('onConversation handler');
		$receiverId = $event->getSender()->getId();
        return (new \Viber\Api\Message\Text())
            ->setSender($botSender)
			->setReceiver($receiverId)
            ->setText(
                "Hi ".$receiverId." "
            )`

**Comment by Bogdaan** [comment]
```
    ->onConversation(function ($event) use ($bot, $botSender, $log) {
        $log->info('onConversation handler');

        return (new \Viber\Api\Message\Text())
            ->setSender($botSender)
            ->setText(
                "Hi ".$event->getUser()->getName()
            );
    })
```

**Comment by beneyraheem** [comment]
Thanks a lot :)
