### ISSUE TITLE
setup 500 Internal Server Error

### ISSUE THREAD

**Issue by antonr45** [Bogdaan/viber-bot-php#50]
Добрый день!
При попытке php setup.php
Error: Remote error: Result[HttpRequest[POST /bots/viber/bot.php HTTP/1.1]@572b5ac2 > HttpResponse[HTTP/1.1 500 Internal Server Error]@1323ed84] null

require_once("./vendor/autoload.php");
use Viber\Client;
$apiKey = 'myapi'; // <- PLACE-YOU-API-KEY-HERE
$webhookUrl = 'https://mysite,ru/bots/viber/bot.php'; // <- PLACE-YOU-HTTPS-URL
try {
    $client = new Client([ 'token' => $apiKey ]);
    $result = $client->setWebhook($webhookUrl);
    echo "Success!\n";
} catch (Exception $e) {
    echo "Error: ". $e->getMessage() ."\n";
}

**Comment by beshur** [comment]
А в чём была проблема?
