### ISSUE TITLE
Не могу запустит setup.php

### ISSUE THREAD

**Issue by farhodhojiev** [Bogdaan/viber-bot-php#51]
Добрый день

Не могу запустить setup.php, при запуске выходит ошибка.

`PHP Fatal error:  Uncaught Error: Call to undefined method Viber\Api\Exception\ApiException::getError() in /var/www/html/viber/setup.php:14
Stack trace:
#0 {main}
  thrown in /var/www/html/viber/setup.php on line 14`

Не как не могу разобраться.

**Comment by ossipov** [comment]
В setup.php на 14й линии поменяй getError() на getMessage()

**Comment by makar4eg1993** [comment]
> В setup.php на 14й линии поменяй getError() на getMessage()

такая же проблема!заменил на getMessage() в итоге получаю Error: Remote error: -
