### ISSUE TITLE
onText ввод русскоязычного текста

### ISSUE THREAD

**Issue by EdgarHubert** [Bogdaan/viber-bot-php#55]
Добрый день! Функция onText обрабатывает только англоязычный ввод текста. А как вводить произвольный текст на русском? как вообще извлечь пользовательский ввод произвольного текста, для дальнейшей обработки, например записи в БД?

**Comment by Bogdaan** [comment]
перехват всех сообщений:
```
        ->on(function ($event) {
            return true; // match all
        }, function ($event) use ($log) {
            $log->info('event: ' . var_export($event, true));
        })
```
