### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by beneyraheem** [Bogdaan/viber-bot-php#6]
Is it possible to repeat a keyboard without writing whole setKeyboard in each. 

like 

$menu = new Keyboard 

and repeat by calling setKeyboard($menu)

**Comment by Bogdaan** [comment]
yes of course

**Comment by beneyraheem** [comment]
$menu = new Keyboard (				
				(new \Viber\Api\Keyboard())
				->setButtons([
					(new \Viber\Api\Keyboard\Button())
					->setActionType('reply')
					->setActionBody('menu')
					->setText('Main Menu')				
				]));

Can you fix this code for me please.

**Comment by Bogdaan** [comment]
```
$menu = (new \Viber\Api\Keyboard())
->setButtons([
  (new \Viber\Api\Keyboard\Button())
  ->setActionType('reply')
  ->setActionBody('menu')
  ->setText('Main Menu')
]);
```

**Comment by beneyraheem** [comment]
great, Thanks a lot for your help.
