### ISSUE TITLE
Не отправляется номер телефона через share-phone с десктопной версии viber

### ISSUE THREAD

**Issue by bogdaan2001** [Bogdaan/viber-bot-php#60]
Здравствуйте! 

Кто-нибудь может подсказать, через кнопку share-phone по мобильному приложению  номер телефона передается без проблем, через десктопную версию программы номер по кнопке не передается, приходит пустота. (десктопная версия зарегистрирована на тот же номер, что и мобильная)

Как отправить номер телефона через viber установленный на обычном PC ?

**Comment by Sergi0Limit** [comment]
та же проблема именно на десктопе

**Comment by Mackiavelly** [comment]
> Здравствуйте!
> 
> Кто-нибудь может подсказать, через кнопку share-phone по мобильному приложению номер телефона передается без проблем, через десктопную версию программы номер по кнопке не передается, приходит пустота. (десктопная версия зарегистрирована на тот же номер, что и мобильная)
> 
> Как отправить номер телефона через viber установленный на обычном PC ?

покажите код приёма данных от пользователя

**Comment by Sergi0Limit** [comment]
кому интересно [тут](https://toster.ru/q/643145) все описано

**Comment by vadimkara** [comment]
message: keyboard is not valid. [instance value ("share-phone") not found in enum (possible values: ["reply","open-url",""])]
А апи поддерживает еще эту функцию? Мне пайлод приходит только с 2 вариантами.

**Comment by Mackiavelly** [comment]
> message: keyboard is not valid. [instance value ("share-phone") not found in enum (possible values: ["reply","open-url",""])]
> А апи поддерживает еще эту функцию? Мне пайлод приходит только с 2 вариантами.

->setMinApiVersion(3)

**Comment by Bogdaan** [comment]
```
We currently don’t have this action type supported on desktop clients.
Our teams are discussing the possibility to add it in future versions. I’ll update you if there are any news on the subject.

To still be able to use this action type, I suggest adding some sort of fallback, in which if the callback is returned without the number, explicitly ask for the user to enter it.
```
