### ISSUE TITLE
Ответ из функции

### ISSUE THREAD

**Issue by n13north** [Bogdaan/viber-bot-php#65]
Добрый день! Не могли бы вы накидать простой пример ответа из функции. Т.Е. по методу ontext вызывается некая функция, и ответ идет из нее. Не могу сообразить как раскидать эти стрелочки из примера, чтобы код упростить. Я VBшник если что, с php сильно на Вы.

**Comment by n13north** [comment]
Сделал таким образом, но теперь приходит около 100 ответов. Куда копать?
`
try {
    $bot = new Bot(['token' => $apiKey]);
    $bot
    ->onConversation(function ($event) use ($bot, $botSender) {
        // это событие будет вызвано, как только пользователь перейдет в чат
        // вы можете отправить "привествие", но не можете посылать более сообщений
        return (new \Viber\Api\Message\Text())
            ->setSender($botSender)
            ->setText("Я робот. Список моих команд можно получить отправив знак '?'");
    })
    ->onText('||si', function ($event) use ($bot) {
        // это событие будет вызвано если пользователь пошлет сообщение 
        // которое совпадет с регулярным выражением
            sendmesage($event->getSender()->getId());   

    })
    ->run();
} catch (Exception $e) {
    // todo - log exceptions
}

function sendmesage($getId) 
{ //begin func

global $bot;

$botSender = new Sender([
    'name' => 'бот-братишка',
    'avatar' => 'http://ncwater.ru/favicon.ico',
]);

            $bot->getClient()->sendMessage(
            (new \Viber\Api\Message\Text())
            ->setSender($botSender)
            ->setReceiver($getId)
            ->setText("тест функции")
        );
    $bot->run();

}//end func
`

**Comment by n13north** [comment]
Может задонатить нужно? Помогите пожалуйста

**Comment by Bogdaan** [comment]
ответа из замыкания нет

пример можете посмотреть в https://github.com/Bogdaan/viber-bot-php/blob/master/examples/bot-plus.php#L65

**Comment by n13north** [comment]
Разобрался, спасибо. Через пример кстати совсем не понятно. Теперь проблема - карусель в цикле кнопки не должна заполнять как клавиатура, или это баг? Ругается на Call to a member function toApiArray() в обработчике карусели. То есть заранее заполненный массив не принимается.

**Comment by Bogdaan** [comment]
приведите пожалуйста пример кода

**Comment by n13north** [comment]
теперь другая ошибка, но суть та же. Аналогичный пример из сэмпла для кейборда работает, а для карусели нет. Моя цель заполнить карусель в цикле.


`function goodslist($pertext,$getId)
{  //begin func
global $bot;
global $botSender;
            $buttons = [];
            for ($i = 0; $i <= 8; $i++) {
                $buttons[] =
                    (new \Viber\Api\Keyboard\Button())
                                   ->setColumns(6)
                                    ->setRows(6)
                                    ->setActionType('reply')
                                    ->setImage('https://rubleshop.ru/ncwater/img/18l.jpg')
                                    ->setActionBody('https://www.google.com')
                                    ->setText('ЗАКАЗАТЬ')
                                    ->setTextSize("large")
                                    ->setTextVAlign("middle")
                                    ->setTextHAlign("middle");
            }

$bot->getClient()->sendMessage(
                        (new \Viber\Api\Message\CarouselContent())
                            ->setSender($botSender)
                            ->setReceiver($getId)
                            ->setButtonsGroupColumns(6)
                            ->setButtonsGroupRows(6)
                            ->setBgColor('#FFFFFF')
                            ->setButtons($buttons[])
                
                            
                    );
}//end func`

**Comment by n13north** [comment]
Добрый день. Нет идей?

**Comment by n13north** [comment]
Спасибо за помощь. Ответ был в размере матрицы. Подбирается от балды. Видимо влияет итоговый размер сообщения. В моем случае работает матрица - группа 6x6 и размер элемента группы 3 ряда на 2 колонки. Максимальное число элементов для меня 36 (цикл от 0 до 35, получается 6 групп полных). И теперь мы подходим к ограничению этого примера в целом: то есть ответ можно послать только в ответ на событие. Иначе никак. Можно ли посылать сообщения не в ответ (не по событию ontext, onconversation)?
