### ISSUE TITLE
Как отправить сообщение в Вайбер, НЕ в ответ на сообщение из Вайбера?

### ISSUE THREAD

**Issue by tsubaku** [Bogdaan/viber-bot-php#67]
Подскажите пожалуйста, как можно отправить сообщение в Вайбер, уже зная id адресата? То есть, человек написал боту, подписался на паблик аккаунт и теперь бот имеет право присылать человеку сообщения. Окей. Но, насколько я разобрался в коде, при попытке отправки run() происходит считывание php://input, и если там нет правильного значения, то отправка не срабатывает.

**Comment by NickChayka** [comment]
Элементарно же.

```
$botSender = new Sender([
    'name' => 'Bot name',
    'avatar' => 'https://your-domain/bot-avatar.png',
]);

$msg = "Hello world!";
$user_id = "<USER_ID>";

try {
    $bot = new Bot(['token' => "<VIBER_API_KEY>"]);
    $bot->getClient()->sendMessage(
        (new \Viber\Api\Message\Text())
              ->setSender($botSender)
              ->setReceiver($user_id)
              ->setText($msg)
        );
    $jret = [
        'success' => true,
        'result' => 'Ok'
    ];
} catch (Exception $e) {
    $jret = [
        'success' => false,
        'result' => 'BOT Exception: '.$e->getMessage()
    ];
}

var_dump($jret);
```
Укажите свой VIBER_API_KEY, имя бота и аватарку. USER_ID у вас должен быть сохранён после того, как юзер подписался на бота (это $USER_ID = $event->getSender()->getId(); ). И всё, при запуске бот отправит этому юзеру текст из $msg.
