### ISSUE TITLE
Не работает отправка телефона.

### ISSUE THREAD

**Issue by berpcor** [Bogdaan/viber-bot-php#69]
Здравствуйте. 
```
->setKeyboard(
    (new \Viber\Api\Keyboard())
        ->setButtons([
            (new \Viber\Api\Keyboard\Button())
                    ->setActionType('share-phone')
                    ->setActionBody('reply')
                    ->setText('Send phone number')
                ])
    )

```
Как это работает?
Логирую все обращения к обработчику запросов от бота. После нажатия на кнопку приходит запрос с вот такой секцией message:

`"message":{"text":"reply","type":"text"}`

А должен быть тип, по-видимому, contact.
Как и где ловить телефон?

В инструкции сказано:

> For ActionType share-phone - api level 3 and above:
> 
> The client will be able to share its phone number via a ContactMessage object.

Где брать этот объект?

**Comment by berpcor** [comment]
->setActionType('share-phone')
Как будто бы вообще ни на что не влияет: убираю его, ввожу `->setActionType('fadsgsdfg)` - 
одно и то же содержание сообщения, которое приходит в обработчик на сервере.

**Comment by Bogdaan** [comment]
Если у вас есть идеи как улучшить README.md: предлагаю оформить MR
