### ISSUE TITLE
How to call from text file?

### ISSUE THREAD

**Issue by beneyraheem** [Bogdaan/viber-bot-php#7]
Is there a way to call from text from a txt file. 

My plan is to add many words to a text file and when a user type anyword from that txt file, a message to send. Like filtering bad words from a file.

Its difficult to add all words in the bot.php file. 

I believe it is possible to explode text and check for preg match

**Comment by Bogdaan** [comment]
You can use this tamplate:
```php
// new line - new word
$badWords = explode("\n", file_get_contents('words.txt'));

// ... init $bot

$bot->on(function (Event $event) use ($badWords) {
            return (
                $event instanceof \Viber\Api\Event\Message
                && array_search($event->getMessage()->getText(), $badWords) !== false
            );
        }, function() {
           // <-- YOU HANDLER HERE
        });
