### ISSUE TITLE
Как получить на сервере сообщение?

### ISSUE THREAD

**Issue by oxoooooo** [Bogdaan/viber-bot-php#75]
Как получить на сервере сообщение отправленное из чат бота?

**Comment by n13north** [comment]
->onText('||si', function ($event) use ($bot, $botSender) {
        // это событие будет вызвано если пользователь пошлет сообщение 
        // которое совпадет с регулярным выражением
        $pertext = $event->getMessage()->getText(); //Вот это как раз полученный текст
        $getId = $event->getSender()->getId(); //а это id чата-юзера
        makedecision($pertext,$getId); //а это процедурка,  в который ты анализируешь текст и че-нибудь делаешь
    }) ->run();
