### ISSUE TITLE
Как получить $event->getSender()->getId(); при подписке на чат?

### ISSUE THREAD

**Issue by oxoooooo** [Bogdaan/viber-bot-php#77]
Как получить $event->getSender()->getId(); при подписке на чат? Автор api писал вроде в "вопросах", что есть некая функция make, но что то я не понял как ее использовать. Пожалуйста подскажите как?

**Comment by n13north** [comment]
> Как получить $event->getSender()->getId(); при подписке на чат? Автор api писал вроде в "вопросах", что есть некая функция make, но что то я не понял как ее использовать. Пожалуйста подскажите как?

получается такая схема - для того чтобы подписаться, нужно написать боту, а тогда срабатывает ontext

**Comment by oxoooooo** [comment]
Но при такой схеме возвращается id при каждом написании в чат и нажатии кнопки, мне нужно именно при подписке

**Comment by n13north** [comment]
А можешь объяснить зачем? Может и мне тогда надо будет)

Для примера посмотрел бота Мумийтроля, там классическая схема - сначала oncoversation-затем жамкаешь подписаться и это уже ontext

**Comment by oxoooooo** [comment]
Ну например, что бы записать viber id в бд юзеру

**Comment by n13north** [comment]
А у тебя в любом случае каждый раз будет запрос в бд с проверкой есть ли этот юзер в бд, так как ты каждый раз не будешь знать от кого пришло сообщение, будешь делать запрос в историю общения

**Comment by oxoooooo** [comment]
Ну наверно ты прав. Спасибо))
