### ISSUE TITLE
Не получается добавить кнопку "отправить контакт"

### ISSUE THREAD

**Issue by BeekeeperVS** [Bogdaan/viber-bot-php#80]
`$keyboard[] =
            (new \Viber\Api\Keyboard\Button())
                ->setActionType('share-phone')
                ->setActionBody('reply')
                ->setText(MessagesTextHelper::findMessage(MessagesTextHelper::BUTTON_TYPE, 'contact'));
        return $keyboard;`
Не получается добавить кнопку такого типа. в чем может быть проблема?

**Comment by n13north** [comment]
$bot->getClient()->sendMessage((new \Viber\Api\Message\Text())
                            ->setSender($botSender)
                            ->setReceiver($getId)
                            ->setMinApiVersion(3)
                            ->setText("Нажмите на кнопку")
                            ->setKeyboard(
                                (new \Viber\Api\Keyboard())
                                    ->setButtons([
                                            (new \Viber\Api\Keyboard\Button())
                                            ->setColumns(6)
                                            ->setRows(1)
                                            ->setBgColor("#fdf8fc")
                                            ->setText('Нажмите, чтобы поделиться номером')
                                            ->setTextHAlign('center')
                                            ->setTextSize('large')
                                            ->setActionType('share-phone')
                                            ->setActionBody('phone_reply'),
                                    ])
                            )
                    );

**Comment by BeekeeperVS** [comment]
Дякую)) вже вирішив проблему)
