### ISSUE TITLE
Как отправить пользователю изображение?

### ISSUE THREAD

**Issue by YevgenZhylenkov** [Bogdaan/viber-bot-php#85]
Как отправить пользователю изображение?

**Comment by ypylypenko** [comment]
`
$client = new Viber\Client([
    'token' => 'your token'
]);

$file = (new File())
                ->setSender($this->getSender())
                ->setReceiver($message->getRecipient())
                ->setSize($message->getFileSize())
                ->setFileName($message->getFileName())
                ->setMedia($message->getPublicUrl());

$result = $this->client->sendMessage($file);
`
