### ISSUE TITLE
Подскажите как  отследить отписку? 

### ISSUE THREAD

**Issue by makar4eg1993** [Bogdaan/viber-bot-php#93]

**Comment by Vanawy** [comment]
насколько я понимаю для этого есть метод `onUnsubscribe`

**Comment by makar4eg1993** [comment]
> насколько я понимаю для этого есть метод `onUnsubscribe`

да, благодарю. Уже разобрался

**Comment by NikitaKobzar** [comment]
Не нашел такой метод... Подскажите, как все же отследить отписку?

**Comment by makar4eg1993** [comment]
> Не нашел такой метод... Подскажите, как все же отследить отписку?
нужно дописать. я в класс bot.php добавил следующий код:

public function onUnSubscribe(\Closure $handler)
    {
        $this->managers[] = new Manager(function (Event $event) {
            return ($event instanceof \Viber\Api\Event\Unsubscribed);
        }, $handler);

        return $this;
    }

**Comment by JPBS060896** [comment]
> > Didn't find such a method ... Tell me how to track the unsubscribe? 
> > need to be added. I added the following code to the bot.php class:
> 
> public function onUnSubscribe(\Closure $handler) { $this->managers[] = new Manager(function (Event $event) { return ($event instanceof \Viber\Api\Event\Unsubscribed); }, $handler);
> 
> ```
>     return $this;
> }
> ```

I tried doing this and call the method on a separate php file but there's no response from the bot? how to use this method?
